### ISSUE TITLE
Fix scrobbler

### ISSUE THREAD

**Issue by aka-charos** [tinuzz/zina#3]
Last.FM  scrobbler isn't working with current release of Zina. 
- How to reproduce: Add your Last.FM credentials ( which by the way I think are saved in plaintext) and listen to a track that has proper id3 tags so Last.FM can parse it. Now go to your Last.FM profile and see the song that you currently listen.
- Expected behavior: Once the song is finished , you should see it on Recently Listened Tracks list.
- Current behavior: The song  in Zina can be seen at the list while playing. But once the song is finished, it disappears from the list.

**Comment by tinuzz** [comment]
Archiving this repository.
